CREATE TABLE items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255)                            NOT NULL,
    found_at    TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_items PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_items_found_at ON items(found_at);
CREATE INDEX IF NOT EXISTS idx_items_created_at ON items(created_at);