CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    login         VARCHAR(255)                            NOT NULL,
    password_hash VARCHAR(255)                            NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE items
    ADD found_by_user_id BIGINT;

ALTER TABLE items
    ALTER COLUMN found_by_user_id SET NOT NULL;

ALTER TABLE items
    ADD CONSTRAINT FK_ITEMS_ON_FOUND_BY_USER FOREIGN KEY (found_by_user_id) REFERENCES users (id);